//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPL_Complaint.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_add_admin> tbl_add_admin { get; set; }
        public virtual DbSet<tbl_assi_product> tbl_assi_product { get; set; }
        public virtual DbSet<tbl_caty> tbl_caty { get; set; }
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_client> tbl_client { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_sadmin> tbl_sadmin { get; set; }
        public virtual DbSet<tbl_state> tbl_state { get; set; }
        public virtual DbSet<tbl_Support_ticket> tbl_Support_ticket { get; set; }
        public virtual DbSet<tbl_ticket_for> tbl_ticket_for { get; set; }
    
        public virtual int Sp_add_admin(string emp_id, string emp_name, string contact_no, string email_id, string pwd, string address, string city, string state, string pincode, string desigination, string department, ObjectParameter accid)
        {
            var emp_idParameter = emp_id != null ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(string));
    
            var emp_nameParameter = emp_name != null ?
                new ObjectParameter("emp_name", emp_name) :
                new ObjectParameter("emp_name", typeof(string));
    
            var contact_noParameter = contact_no != null ?
                new ObjectParameter("contact_no", contact_no) :
                new ObjectParameter("contact_no", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(string));
    
            var desiginationParameter = desigination != null ?
                new ObjectParameter("desigination", desigination) :
                new ObjectParameter("desigination", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_add_admin", emp_idParameter, emp_nameParameter, contact_noParameter, email_idParameter, pwdParameter, addressParameter, cityParameter, stateParameter, pincodeParameter, desiginationParameter, departmentParameter, accid);
        }
    
        public virtual int Sp_add_ticket(string date, string select_product, string ticket_for, string message, ObjectParameter accid)
        {
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var select_productParameter = select_product != null ?
                new ObjectParameter("select_product", select_product) :
                new ObjectParameter("select_product", typeof(string));
    
            var ticket_forParameter = ticket_for != null ?
                new ObjectParameter("ticket_for", ticket_for) :
                new ObjectParameter("ticket_for", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_add_ticket", dateParameter, select_productParameter, ticket_forParameter, messageParameter, accid);
        }
    
        public virtual int Sp_addclient(string company_id, string company_name, string contact_person, string address, string city, string state, string pincode, string contact_no, string email_id, string pwd, string gst_no, string pan_no, ObjectParameter accid)
        {
            var company_idParameter = company_id != null ?
                new ObjectParameter("company_id", company_id) :
                new ObjectParameter("company_id", typeof(string));
    
            var company_nameParameter = company_name != null ?
                new ObjectParameter("company_name", company_name) :
                new ObjectParameter("company_name", typeof(string));
    
            var contact_personParameter = contact_person != null ?
                new ObjectParameter("contact_person", contact_person) :
                new ObjectParameter("contact_person", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(string));
    
            var contact_noParameter = contact_no != null ?
                new ObjectParameter("contact_no", contact_no) :
                new ObjectParameter("contact_no", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var gst_noParameter = gst_no != null ?
                new ObjectParameter("gst_no", gst_no) :
                new ObjectParameter("gst_no", typeof(string));
    
            var pan_noParameter = pan_no != null ?
                new ObjectParameter("pan_no", pan_no) :
                new ObjectParameter("pan_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_addclient", company_idParameter, company_nameParameter, contact_personParameter, addressParameter, cityParameter, stateParameter, pincodeParameter, contact_noParameter, email_idParameter, pwdParameter, gst_noParameter, pan_noParameter, accid);
        }
    
        public virtual int Sp_addproduct(string product_id, string product_category, string product_name, string description, ObjectParameter accid)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var product_categoryParameter = product_category != null ?
                new ObjectParameter("product_category", product_category) :
                new ObjectParameter("product_category", typeof(string));
    
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_addproduct", product_idParameter, product_categoryParameter, product_nameParameter, descriptionParameter, accid);
        }
    
        public virtual int Sp_assiproduct(string select_client_id, string select_product, string select_client, string select_emp, string select_project_supp, string installation_date, string amc_date, string amount, string amc_per, ObjectParameter accid)
        {
            var select_client_idParameter = select_client_id != null ?
                new ObjectParameter("select_client_id", select_client_id) :
                new ObjectParameter("select_client_id", typeof(string));
    
            var select_productParameter = select_product != null ?
                new ObjectParameter("select_product", select_product) :
                new ObjectParameter("select_product", typeof(string));
    
            var select_clientParameter = select_client != null ?
                new ObjectParameter("select_client", select_client) :
                new ObjectParameter("select_client", typeof(string));
    
            var select_empParameter = select_emp != null ?
                new ObjectParameter("select_emp", select_emp) :
                new ObjectParameter("select_emp", typeof(string));
    
            var select_project_suppParameter = select_project_supp != null ?
                new ObjectParameter("select_project_supp", select_project_supp) :
                new ObjectParameter("select_project_supp", typeof(string));
    
            var installation_dateParameter = installation_date != null ?
                new ObjectParameter("installation_date", installation_date) :
                new ObjectParameter("installation_date", typeof(string));
    
            var amc_dateParameter = amc_date != null ?
                new ObjectParameter("amc_date", amc_date) :
                new ObjectParameter("amc_date", typeof(string));
    
            var amountParameter = amount != null ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(string));
    
            var amc_perParameter = amc_per != null ?
                new ObjectParameter("amc_per", amc_per) :
                new ObjectParameter("amc_per", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_assiproduct", select_client_idParameter, select_productParameter, select_clientParameter, select_empParameter, select_project_suppParameter, installation_dateParameter, amc_dateParameter, amountParameter, amc_perParameter, accid);
        }
    
        public virtual int sp_Change_Pass(string email, string newPass, ObjectParameter accid)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var newPassParameter = newPass != null ?
                new ObjectParameter("newPass", newPass) :
                new ObjectParameter("newPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Change_Pass", emailParameter, newPassParameter, accid);
        }
    
        public virtual ObjectResult<sp_check_AMC_Result> sp_check_AMC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_check_AMC_Result>("sp_check_AMC");
        }
    
        public virtual ObjectResult<sp_check_AMC_New_Result> sp_check_AMC_New()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_check_AMC_New_Result>("sp_check_AMC_New");
        }
    
        public virtual int Sp_Complete_ticket(Nullable<int> id, string message, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Complete_ticket", idParameter, messageParameter, accid);
        }
    
        public virtual int Sp_Delete_admin(Nullable<int> id, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_admin", idParameter, accid);
        }
    
        public virtual int Sp_Delete_assi_product(Nullable<int> id, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_assi_product", idParameter, accid);
        }
    
        public virtual int Sp_Delete_client(Nullable<int> id, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_client", idParameter, accid);
        }
    
        public virtual int Sp_Delete_product(Nullable<int> id, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_product", idParameter, accid);
        }
    
        public virtual ObjectResult<sp_New_check_AMC_Result> sp_New_check_AMC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_New_check_AMC_Result>("sp_New_check_AMC");
        }
    
        public virtual int Sp_Update_admin(Nullable<int> id, string emp_id, string emp_name, string contact_no, string email_id, string pwd, string address, string city, string state, string pincode, string desigination, string department, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var emp_idParameter = emp_id != null ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(string));
    
            var emp_nameParameter = emp_name != null ?
                new ObjectParameter("emp_name", emp_name) :
                new ObjectParameter("emp_name", typeof(string));
    
            var contact_noParameter = contact_no != null ?
                new ObjectParameter("contact_no", contact_no) :
                new ObjectParameter("contact_no", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(string));
    
            var desiginationParameter = desigination != null ?
                new ObjectParameter("desigination", desigination) :
                new ObjectParameter("desigination", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_admin", idParameter, emp_idParameter, emp_nameParameter, contact_noParameter, email_idParameter, pwdParameter, addressParameter, cityParameter, stateParameter, pincodeParameter, desiginationParameter, departmentParameter, accid);
        }
    
        public virtual int Sp_Update_assi_product(Nullable<int> id, string select_client_id, string select_product, string select_client, string select_emp, string select_project_supp, string installation_date, string amc_date, string amount, string amc_per, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var select_client_idParameter = select_client_id != null ?
                new ObjectParameter("select_client_id", select_client_id) :
                new ObjectParameter("select_client_id", typeof(string));
    
            var select_productParameter = select_product != null ?
                new ObjectParameter("select_product", select_product) :
                new ObjectParameter("select_product", typeof(string));
    
            var select_clientParameter = select_client != null ?
                new ObjectParameter("select_client", select_client) :
                new ObjectParameter("select_client", typeof(string));
    
            var select_empParameter = select_emp != null ?
                new ObjectParameter("select_emp", select_emp) :
                new ObjectParameter("select_emp", typeof(string));
    
            var select_project_suppParameter = select_project_supp != null ?
                new ObjectParameter("select_project_supp", select_project_supp) :
                new ObjectParameter("select_project_supp", typeof(string));
    
            var installation_dateParameter = installation_date != null ?
                new ObjectParameter("installation_date", installation_date) :
                new ObjectParameter("installation_date", typeof(string));
    
            var amc_dateParameter = amc_date != null ?
                new ObjectParameter("amc_date", amc_date) :
                new ObjectParameter("amc_date", typeof(string));
    
            var amountParameter = amount != null ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(string));
    
            var amc_perParameter = amc_per != null ?
                new ObjectParameter("amc_per", amc_per) :
                new ObjectParameter("amc_per", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_assi_product", idParameter, select_client_idParameter, select_productParameter, select_clientParameter, select_empParameter, select_project_suppParameter, installation_dateParameter, amc_dateParameter, amountParameter, amc_perParameter, accid);
        }
    
        public virtual int Sp_Update_client(Nullable<int> id, string company_id, string company_name, string contact_person, string address, string city, string state, string pincode, string contact_no, string email_id, string pwd, string gst_no, string pan_no, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var company_idParameter = company_id != null ?
                new ObjectParameter("company_id", company_id) :
                new ObjectParameter("company_id", typeof(string));
    
            var company_nameParameter = company_name != null ?
                new ObjectParameter("company_name", company_name) :
                new ObjectParameter("company_name", typeof(string));
    
            var contact_personParameter = contact_person != null ?
                new ObjectParameter("contact_person", contact_person) :
                new ObjectParameter("contact_person", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(string));
    
            var contact_noParameter = contact_no != null ?
                new ObjectParameter("contact_no", contact_no) :
                new ObjectParameter("contact_no", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var gst_noParameter = gst_no != null ?
                new ObjectParameter("gst_no", gst_no) :
                new ObjectParameter("gst_no", typeof(string));
    
            var pan_noParameter = pan_no != null ?
                new ObjectParameter("pan_no", pan_no) :
                new ObjectParameter("pan_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_client", idParameter, company_idParameter, company_nameParameter, contact_personParameter, addressParameter, cityParameter, stateParameter, pincodeParameter, contact_noParameter, email_idParameter, pwdParameter, gst_noParameter, pan_noParameter, accid);
        }
    
        public virtual int Sp_Update_product(Nullable<int> id, string product_id, string product_category, string product_name, string description, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var product_categoryParameter = product_category != null ?
                new ObjectParameter("product_category", product_category) :
                new ObjectParameter("product_category", typeof(string));
    
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_product", idParameter, product_idParameter, product_categoryParameter, product_nameParameter, descriptionParameter, accid);
        }
    
        public virtual int Sp_Update_ticket_status(Nullable<int> id, string message, ObjectParameter accid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_ticket_status", idParameter, messageParameter, accid);
        }
    }
}
