//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPL_Complaint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_add_admin
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string contact_no { get; set; }
        public string email_id { get; set; }
        public string pwd { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string desigination { get; set; }
        public string department { get; set; }
    }
}
