//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPL_Complaint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assi_product
    {
        public int id { get; set; }
        public string select_client_id { get; set; }
        public string select_product { get; set; }
        public string select_client { get; set; }
        public string select_emp { get; set; }
        public string select_project_supp { get; set; }
        public string installation_date { get; set; }
        public string amc_date { get; set; }
        public string amount { get; set; }
        public string amc_per { get; set; }
    }
}
