//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPL_Complaint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_designation
    {
        public int id { get; set; }
        public string designation_id { get; set; }
        public string designation_name { get; set; }
    }
}
