//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPL_Complaint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Support_ticket
    {
        public int id { get; set; }
        public string date { get; set; }
        public string select_product { get; set; }
        public string ticket_for { get; set; }
        public string message { get; set; }
        public string status { get; set; }
    }
}
